name = "SimpleArgParse2"
uuid = "e3fa765b-3027-4ef3-bb12-e639c1e60c6e"
authors = ["Adam Erickson <adam.michael.erickson@gmail.com>", "Eben60"]
version = "0.1.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
Compat = "4.10"
OrderedCollections = "1.5"
PrecompileTools = "1"
julia = "1.9"
