name = "SimpleArgParse"
uuid = "4c739d64-e22d-44e1-ada1-53a1c3c0e953"
authors = ["Adam Erickson <adam.michael.erickson@gmail.com>"]
version = "1.0.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.0"
