name = "SimpleArgParse"
uuid = "4c739d64-e22d-44e1-ada1-53a1c3c0e953"
authors = ["Adam Erickson <adam.michael.erickson@gmail.com>", "Eben60"]
version = "2.0.0-alpha"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
Compat = "4.10"
OrderedCollections = "1.5"
PrecompileTools = "1"
julia = "1.6"
