name = "YAArguParser"
uuid = "bcbd4c87-030e-4da8-a7f0-f342a29caad3"
authors = ["Adam Erickson <adam.michael.erickson@gmail.com>", "Eben60"]
version = "2.0.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[weakdeps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[extensions]
ParseDatesExt = "Dates"

[compat]
Compat = "4.10"
Dates = "<0.0.1, 1"
OrderedCollections = "1.5"
PrecompileTools = "1"
julia = "1.10"
