name: GitHub Actions
run-name: ${{ github.actor }}
on: [push]
jobs:
  GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job automatically triggered by event ${{ github.event_name }}."
      - run: echo "Job now running on a ${{ runner.os }} server hosted on GitHub."
      - run: echo "The name of the branch is ${{ github.ref }} and the repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "${{ github.repository }} repository has been cloned to the runner."
      - run: echo "Workflow ready to test code on the runner."
      - run: echo "The job status is ${{ job.status }}."
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        #env:
        #  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
